radio.setGroup(12)
RamieRobota.WyswietlIkone(IconNames.Happy)
basic.showIcon(IconNames.Happy)
RamieRobota.InicjujRamieRobota()
basic.pause(2000)
RamieRobota.WyswietlIkone(IconNames.Yes)
basic.showIcon(IconNames.Yes)
basic.showString("G")
RamieRobota.RamieDoGory()
basic.pause(5000)
basic.showString("Z")
RamieRobota.ZamknijSzczeki()
basic.pause(5000)
basic.showString("L")
RamieRobota.RamieWLewo()
basic.pause(5000)
basic.showString("O")
RamieRobota.OtworzSzczeki()
basic.pause(5000)
basic.showString("D")
RamieRobota.RamieNaDol()
basic.pause(5000)
basic.showString("Z")
RamieRobota.ZamknijSzczeki()
basic.pause(5000)
basic.showString("G")
RamieRobota.RamieDoGory()
basic.pause(5000)
basic.showString("P")
RamieRobota.RamieWPrawo()


basic.forever(function () {

})
 